### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by pacmancoder** [kbladin/global_illumination#1]
Hello! What is the license for the project?

I want to fork this ray tracer and integrate it to my [dcdr](https://github.com/pacmancoder/dcdr) (this project is mainly focused on distributed ray tracing over network idea presentation and not on raytracing techniques itself). It looks like your implementation is enough for my purpose, and it can be easily integrated to dcdr code base.

**Comment by kbladin** [comment]
Hey. Sorry for late reply. Use as you wish and credit where appropriate.
Best

**Comment by pacmancoder** [comment]
Thanks for the reply 👍
